# Generated by Django 2.1.7 on 2019-03-04 15:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reusable', models.BooleanField(default=False)),
                ('merchant_session_key', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=255)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=4)),
                ('card_identifier', models.CharField(max_length=100)),
                ('card_identifier_expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('billing_address_1', models.CharField(max_length=255)),
                ('billing_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_country', models.CharField(choices=[('IE', 'Ireland'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=2)),
                ('billing_postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('billing_state', models.CharField(blank=True, choices=[('AL', 'Alabama')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Payment', 'Payment'), ('Repeat', 'Repeat')], max_length=8)),
                ('vendor_tx_code', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('GBP', 'Pound Sterling')], max_length=3)),
                ('description', models.TextField()),
                ('status_code', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=36, null=True)),
                ('retrieval_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_authorisation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('acs_url', models.URLField(blank=True, null=True)),
                ('pareq', models.TextField(blank=True, null=True)),
                ('pares', models.TextField(blank=True, null=True)),
                ('secure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=4, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('card_identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sagepaypi.CardIdentifier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.CharField(max_length=100)),
                ('status_code', models.IntegerField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sagepaypi.Transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cardidentifier',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_identifiers', to='sagepaypi.Customer'),
        ),
    ]
