# Generated by Django 2.1.7 on 2019-03-05 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sagepaypi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='error_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='instruction',
            field=models.CharField(blank=True, db_index=True, help_text='The instruction to either release, abort or void a transaction.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='instruction_created_at',
            field=models.DateTimeField(blank=True, help_text='The date in which the instruction was requested.', null=True),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='card_identifier',
            field=models.CharField(help_text='The card identifier key sent back from Sage Pay.', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='card_identifier_expiry',
            field=models.DateTimeField(help_text='The datetime in which a transaction must be submitted to Sage Pay by before the card identifier becomes invalid.'),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='card_type',
            field=models.CharField(help_text='The type of card reported by Sage Pay.', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='expiry_date',
            field=models.CharField(help_text='The expiry date of the card, format "MMYY".', max_length=4),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='last_four_digits',
            field=models.CharField(help_text='The last four digits of the card.', max_length=4),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='merchant_session_key',
            field=models.CharField(help_text='The merchant session key that was used to register the card identifier with Sage Pay.', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='reusable',
            field=models.BooleanField(default=False, help_text='Indicates the card identifier can be used in future transactions.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_postal_code',
            field=models.CharField(blank=True, help_text='Required for all countries except Ireland', max_length=12, null=True, verbose_name='Postal/Zip Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama')], help_text='Required only if country is United States', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='acs_url',
            field=models.URLField(blank=True, help_text='The url to redirect to for a transaction that requires 3-D authentication.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(help_text='The amount charged in the smallest currency unit. e.g 100 pence to charge £1.00.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_authorisation_code',
            field=models.CharField(blank=True, help_text='The authorisation code returned from the merchant bank.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_identifier',
            field=models.ForeignKey(help_text='The card identifier used for the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sagepaypi.CardIdentifier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pound Sterling')], help_text='Currency of transaction, e.g "Pounds Sterling".', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(help_text='Description used against the transaction on Sage Pay.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pareq',
            field=models.TextField(blank=True, help_text='A Base64 encoded, encrypted message that contains the transaction details. This needs to be passed to the issuing bank as part of the 3-D Secure authentication.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pares',
            field=models.TextField(blank=True, help_text='A Base64 encoded, encrypted message sent back by the issuing bank to your TermUrl at the end of the 3-D Secure authentication process.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='retrieval_reference',
            field=models.CharField(blank=True, help_text='Sage Pay unique Authorisation Code for a successfully authorised transaction. Only present if status is Ok.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='secure_status',
            field=models.CharField(blank=True, help_text='The 3-D Secure status of the transaction, if applied.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, help_text='The current status of the transaction on Sage Pay.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_code',
            field=models.CharField(blank=True, help_text='The current status code of the transaction on Sage Pay.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_detail',
            field=models.CharField(blank=True, help_text='The current status detail of the transaction on Sage Pay.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='The transaction id on Sage Pay.', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Repeat', 'Repeat'), ('Deferred', 'Deferred')], help_text='Type of transaction, e.g "Payment".', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor_tx_code',
            field=models.CharField(default=uuid.uuid4, help_text='The unique vendor tx code used for the transaction.', max_length=40, unique=True),
        ),
    ]
