# Generated by Django 2.1.7 on 2019-03-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagepaypi', '0002_auto_20190305_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_transaction',
            field=models.ForeignKey(blank=True, help_text='The referring transaction used when a "Repeat" transaction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sagepaypi.Transaction'),
        ),
    ]
