# Generated by Django 2.1.7 on 2019-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagepaypi', '0002_auto_20190309_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidentifier',
            name='billing_country',
            field=models.CharField(max_length=2, verbose_name='Billing country'),
        ),
        migrations.AlterField(
            model_name='cardidentifier',
            name='billing_state',
            field=models.CharField(blank=True, help_text='Required only if country is United States', max_length=2, null=True, verbose_name='Billing state'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(help_text='Currency code of the transaction, e.g "GBP = Pounds Sterling".', max_length=3, verbose_name='Currency'),
        ),
    ]
