# Generated by Django 3.2.15 on 2022-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagepaypi', '0003_auto_20190312_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionresponse',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Data'),
        ),
    ]
