# Generated by Django 2.1.7 on 2019-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagepaypi', '0003_transaction_reference_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Deferred', 'Deferred'), ('Repeat', 'Repeat'), ('Refund', 'Refund')], help_text='Type of transaction, e.g "Payment".', max_length=8),
        ),
    ]
